#ifndef MOTOR_DEBUG_CONFIG_H
#define MOTOR_DEBUG_CONFIG_H

#define MOTOR_DEBUG_PROTOCOL_DJI          (0U)
#define MOTOR_DEBUG_PROTOCOL_ROBSTRIDE    (1U)

#ifndef MOTOR_DEBUG_PROTOCOL
#define MOTOR_DEBUG_PROTOCOL              MOTOR_DEBUG_PROTOCOL_ROBSTRIDE
#endif

#ifndef MOTOR_DEBUG_CAN_CHANNEL
#define MOTOR_DEBUG_CAN_CHANNEL           (2U)
#endif

#if (MOTOR_DEBUG_PROTOCOL != MOTOR_DEBUG_PROTOCOL_DJI) && \
    (MOTOR_DEBUG_PROTOCOL != MOTOR_DEBUG_PROTOCOL_ROBSTRIDE)
#error "MOTOR_DEBUG_PROTOCOL must be MOTOR_DEBUG_PROTOCOL_DJI or MOTOR_DEBUG_PROTOCOL_ROBSTRIDE"
#endif

#if (MOTOR_DEBUG_CAN_CHANNEL < 1U) || (MOTOR_DEBUG_CAN_CHANNEL > 3U)
#error "MOTOR_DEBUG_CAN_CHANNEL must be 1, 2, or 3"
#endif

#endif
