#ifndef PID_CONFIG_H
#define PID_CONFIG_H

#define PID_POSITION_VARIANT_BASIC       (0U)
#define PID_POSITION_VARIANT_ADVANCED    (1U)

#if !defined(PID_POSITION_CONFIG_VARIANT) && defined(PID_CONFIG_VARIANT)
#define PID_POSITION_CONFIG_VARIANT      PID_CONFIG_VARIANT
#endif

#ifndef PID_POSITION_CONFIG_VARIANT
#define PID_POSITION_CONFIG_VARIANT      PID_POSITION_VARIANT_BASIC
#endif

#if (PID_POSITION_CONFIG_VARIANT != PID_POSITION_VARIANT_BASIC) && \
    (PID_POSITION_CONFIG_VARIANT != PID_POSITION_VARIANT_ADVANCED)
#error "PID_POSITION_CONFIG_VARIANT must be PID_POSITION_VARIANT_BASIC or PID_POSITION_VARIANT_ADVANCED"
#endif

#endif
